Покажемо залежність AQI від pm2.5, pm10, o3, so2, co

```{r}
library(dplyr)
library(boot)
library(readr)
library(knitr)
library(tibble)
library(ggplot2)
library(stringr)
library(tidyr)
library(forcats)
library(here)

df <- readRDS(here("data", "processed", "air_quality_trimmed.rds"))
```


```{r}
summary(df)
```

```{r}
plot_var <- function(name, xscale, yscale) {
  p <- ggplot(df, aes(x = .data[[name]], y = aqi)) +
    geom_point() +
    labs(x = name, y = 'AQI') +
    scale_x_continuous(limits = xscale) +
    scale_y_continuous(limits = yscale)

  ggsave(
    filename = here("plots", "lab3", "initial",  paste(name, ".png", sep = '', collapse = '')), 
    plot = p, 
    width = 16, height = 10,
    bg = "white",
    dpi = 200)
}

plot_var("pm2.5", xscale=c(0, 100), yscale=c(0, 250))
plot_var("pm10", xscale=c(0, 600), yscale=c(0, 250))
plot_var("o3", xscale=NULL, yscale=c(0, 250))
plot_var("so2", xscale=c(0, 100), yscale=c(0, 250))
plot_var("co", xscale=c(0, 6), yscale=c(0, 250))
```

```{r}
plot_var_with_lm <- function(name, xscale, yscale) {
  p <- ggplot(df, aes(x = .data[[name]], y = aqi)) +
    geom_point() +
    stat_smooth(method = "lm", col = "red") +
    labs(x = name, y = 'AQI') +
    scale_x_continuous(limits = xscale) +
    scale_y_continuous(limits = yscale)

  ggsave(
    filename = here("plots", "lab3", "initial",  paste(name, "-lm.png", sep = '', collapse = '')), 
    plot = p, 
    width = 16, height = 10,
    bg = "white",
    dpi = 200)
}

plot_var_with_lm("pm2.5", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_lm("pm10", xscale=c(0, 600), yscale=c(0, 250))
plot_var_with_lm("o3", xscale=NULL, yscale=c(0, 250))
plot_var_with_lm("so2", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_lm("co", xscale=c(0, 6), yscale=c(0, 250))

```

```{r}
plot_var_with_transform <- function (name, f, filter, file_name, xscale, yscale) {
  xy <- tibble(x = df[[name]], y = df$aqi) %>% na.omit() %>% filter()

  y <- xy$y
  x <- xy$x

  model <- lm(y ~ I(f(x)))

  spline_df <- tibble(x = x %>% unique(), `f(x)` = f(x))
  spline_df$prediction <- predict(model, newdata = spline_df)

  p <- ggplot(xy, aes(x = x, y = y)) +
    geom_point() +
    geom_line(aes(x = x, y = prediction), data = spline_df, color = "red") + 
    labs(x = name, y = 'AQI') +
    scale_x_continuous(limits = xscale) +
    scale_y_continuous(limits = yscale)

  ggsave(
    filename = here("plots", "lab3", "initial",  file_name), 
    plot = p, 
    width = 16, height = 10,
    bg = "white",
    dpi = 200)
}
```

```{r}
plot_var_with_log_lm <- function(name, xscale, yscale) {
  plot_var_with_transform(
    name, 
    log, 
    \(t) t[t$x > 0, ], 
    paste(name, "-log-lm.png", sep = '', collapse = ''), 
    xscale, yscale
  )
}

plot_var_with_log_lm("pm2.5", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_log_lm("pm10", xscale=c(0, 600), yscale=c(0, 250))
plot_var_with_log_lm("o3", xscale=NULL, yscale=c(0, 250))
plot_var_with_log_lm("so2", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_log_lm("co", xscale=c(0, 6), yscale=c(0, 250))
```

```{r}
plot_var_with_square_lm <- function(name, xscale, yscale) {
  plot_var_with_transform(
    name, 
    \(x) x + x^2, 
    \(t) t, 
    paste(name, "-sq-lm.png", sep = '', collapse = ''), 
    xscale, yscale
  )
}

plot_var_with_square_lm("pm2.5", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_square_lm("pm10", xscale=c(0, 600), yscale=c(0, 250))
plot_var_with_square_lm("o3", xscale=NULL, yscale=c(0, 250))
plot_var_with_square_lm("so2", xscale=c(0, 100), yscale=c(0, 250))
plot_var_with_square_lm("co", xscale=c(0, 6), yscale=c(0, 250))
```

