Перевіримо модель на стійкість додаючи логаритми та степені:

```{r}
library(dplyr)
library(boot)
library(readr)
library(knitr)
library(tibble)
library(ggplot2)
library(stringr)
library(tidyr)
library(forcats)
library(here)
library(fixest)
library(modelsummary)

df <- readRDS(here("data", "processed", "air_quality_smooth.rds"))
df$year <- as.numeric(format(df$date, '%Y'))

counties <- df %>%
  group_by(county) %>%
  summarize(aqi = mean(aqi, na.rm = TRUE)) %>%
  ungroup() %>%
  arrange(desc(aqi)) %>%
  head(n = 8)

counties <- counties$county

df_counties <- df %>% subset(county %in% counties)
```

```{r}
plot_dep <- function (model, spline_df, name) {
  # spline_df <- unique(spline_df)
  spline_df$y <- predict(model, spline_df)

  spline_df <- spline_df %>% subset(county %in% counties)

  p <- ggplot(df_counties, aes(x = windspeed, y = aqi)) +
    geom_point() +
    geom_line(aes(x = windspeed, y = y), spline_df, color = "red", linewidth=1.5) +
    facet_wrap(~county, ncol = 4) +
    labs(x = "Швидкість вітру", y = "AQI")

  ggsave(
    here("plots", "lab3", paste(name, "-aqi.png", sep = '', collapse = '')),
    p,
    width = 17,
    height = 10,
    bg = "white")
}
```

Покажемо залежність AQI від windspeed

```{r}
model <- feols(aqi ~ windspeed | county, data = df)

spline_df <- tibble(
  windspeed = df$windspeed,
  county = df$county
)

plot_dep(model, spline_df, "windspeed")
```

Покажемо залежність AQI від log(windspeed):

```{r}
model <- feols(aqi ~ I(log(windspeed)) | county, data = df)

spline_df <- tibble(
  windspeed = df$windspeed,
  county = df$county,
  `log(windspeed)` = log(windspeed)
)

plot_dep(model, spline_df, "log(windspeed)")
```

Покажемо залежність AQI від windspeed^2:

```{r}
model <- feols(aqi ~ I(windspeed^2) | county, data = df)

spline_df <- tibble(
  windspeed = df$windspeed,
  county = df$county,
  `windspeed^2` = windspeed^2
)

plot_dep(model, spline_df, "windspeed^2")
```

Покажемо залежність AQI від windspeed^3:

```{r}
model <- feols(aqi ~ I(windspeed^3) | county, data = df)

spline_df <- tibble(
  windspeed = df$windspeed,
  county = df$county,
  `windspeed^3` = windspeed^3
)

plot_dep(model, spline_df, "windspeed^3")
```

```{r}
modelsummary(list(
  "1" = feols(aqi ~ after_reform + windspeed | county, data = df),
  "2" = feols(aqi ~ after_reform + log(windspeed) | county, data = df),
  "3" = feols(aqi ~ after_reform + windspeed^2 | county, data = df),
  "4" = feols(aqi ~ after_reform + windspeed^3 | county, data = df)
), stars = TRUE, output="latex")
```
