```{r setup, include = FALSE}
library(tidyverse)
library(here)
library(zeallot)

theme_set(
  theme_minimal() +
  theme(
    text = element_text(size = 22),
    plot.title = element_text(margin = margin(0, 0, 30, 0), hjust = 0.5),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 10, 0, 0))
  )
)

dir.create(here("plots", "question3"), recursive = TRUE, showWarnings = FALSE)

splitAt <- function(x, pos) {
  split(x, cumsum(seq_along(x) %in% c(pos))) %>%
  unname()
}
```

# Завантаженя датасету з файлу

```{r}
df <- readRDS(here("data", "processed", "air_quality_tidy.RDS"))
```

# Залежність aqi від часу доби

```{r}
df_daytime <- df %>%
  mutate(
    daytime = factor(
      lubridate::hour(date) %/% 3,
      labels = c("00-03", "03-06", "06-09", "09-12", "12-15", "15-18", "18-21", "21-24")
    )
  )
print(df_daytime[, "daytime"])
```

Якість повітря трохи покращується у другій половині дня

```{r}
p <- df_daytime %>%
  ggplot(aes(x = daytime, y = log(aqi))) +
    geom_boxplot(na.rm = TRUE) +
    labs(x = "Інтервал часу (год)", title = "Зміна якості повітря впродовж доби")

ggsave(
  here("plots", "question3", "box.png"), p,
  bg = "white",
  dpi = 200,
  width = 10, height = 10
)
```

Графіки для кожного county

```{r}
plot_box_county <- function(input_df) {
  ggplot(input_df, aes(x = daytime, y = log(aqi))) +
  geom_boxplot(na.rm = TRUE) +
  labs(
    x = "Інтервал часу (год)",
    title = "Зміна aqi впродовж доби"
  ) +
  facet_wrap(~county, ncol = 4, scales = "free") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust = 0.25))
}

p <- plot_box_county(df_daytime)

ggsave(
  here("plots", "question3", "county-box.png"), 
  p, 
  width = 10,
  height = 15,
  bg = "white", dpi = 200
)
```

Для презентації:

```{r}
names <- unique(df_daytime$county)
c(counties_1, counties_2)  %<-% splitAt(names, ceiling(length(names) / 2))

p1 <- plot_box_county(df_daytime[df_daytime$county %in% counties_1, ])
p2 <- plot_box_county(df_daytime[df_daytime$county %in% counties_2, ])

ggsave(
  here("plots", "question3", "county-box-p1.png"), 
  plot = p1, 
  width = 16, height = 10,
  bg = "white",
  dpi = 200)

ggsave(
  here("plots", "question3", "county-box-p2.png"), 
  plot = p2, 
  width = 16, height = 10,
  bg = "white",
  dpi = 200)
```