---
Питання №2
Як зміни в концентрації озону ($O_3$)  та $SO_2$ впливають на загальний рівень забруднення повітря (AQI)?
Крім цього додано графіки інших забруднбвачів, для загального розуміння
---

```{r setup, include = FALSE}
library(tidyverse)
library(skimr)
library(ggplot2)
library(naniar)
library(GGally)
library(corrplot)
library(gridExtra)
library(ggpubr)
library(viridis)
library(here)

theme_set(
  theme_minimal() +
  theme(
    text = element_text(size = 14),
    plot.title = element_text(margin = margin(0, 0, 30, 0), hjust = 0.5),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 10, 0, 0))
  )
)

dir.create(here("plots", "question2"), recursive = TRUE, showWarnings = FALSE)
```

```{r}
set.seed(0)
df <- readRDS(here("data", "processed", "air_quality_trimmed.rds")) %>% slice_sample(n=100000)
```

# Boxplot (аналіз викидів та розподілу всіх показників забруднення)

```{r}
boxplot_pollutants <- df %>%
  select(so2, nox, co, o3, no2, no) %>%
  pivot_longer(cols = everything(), names_to = "pollutant", values_to = "value") %>%
  ggplot(aes(x = pollutant, y = value, fill = pollutant)) +
  geom_boxplot() +
  scale_y_log10() +
  labs(title = "Розподіл забруднюючих речовин (Boxplot)", x = "Забруднювач", y = "Концентрація (log scale)")

ggsave(here("plots", "question2", "boxplot_pollutants.png"), boxplot_pollutants, dpi = 200)
```

# розподіл для o3 (гістограма)

```{r}
o3_plot <- ggplot(df, aes(x = o3)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black") +
  labs(title = "Розподіл o3 (озон)", x = "о3", y = "Частота")

ggsave(here("plots", "question2", "o3_plot.png"), o3_plot, dpi = 200)
```
# за потреби можна додати інші забруднювачі

```{r}
so2_plot <- ggplot(df, aes(x = so2)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black") +
  labs(title = "Розподіл SO2", x = "so2", y = "Частота")

ggsave(here("plots", "question2", "so2_plot.png"), so2_plot, dpi = 200)
```

# Діаграма розсіювання AQI ~ o3

```{r}
scatter_plot <- ggplot(df, aes(x = o3, y = aqi)) +
  geom_point(alpha = 0.5, color = "blue") +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Залежність AQI від o3")

ggsave(here("plots", "question2", "scatter_plot.png"), scatter_plot, dpi = 200)

```

# Розподіли O3 і SO2 по місяцях

```{r}
df_seasonal <- df %>%
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  mutate(o3_median = median(o3, na.rm = TRUE), .by = month)

seasonal_plot <- df_seasonal %>%
  ggplot(aes(x = month, y = o3, fill = o3_median)) +
  geom_boxplot() +
  labs(title = "Кількість O3 по місяцях", x = "Місяць", y = "O3") + 
  scale_fill_viridis(option = "viridis", name = "Медіана", direction = -1)

ggsave(here("plots", "question2", "seasonal_o3.png"), seasonal_plot, bg = "white", dpi = 200)
```

```{r}
df_seasonal <- df %>%
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  mutate(log_so2 = log(so2)) %>% 
  mutate(log_so2_median = median(log_so2, na.rm = TRUE), .by = month)

seasonal_plot <- df_seasonal %>%
  ggplot(aes(x = month, y = log_so2, fill = log_so2_median)) +
  geom_boxplot() +
  labs(title = "Кількість SO2 по місяцях", x = "Місяць", y = "log(SO2)") + 
  scale_fill_viridis(option = "viridis", name = "Медіана", direction = -1)

ggsave(here("plots", "question2", "seasonal_so2.png"), seasonal_plot, bg = "white", dpi = 200)
```

---
додавати QQ-графіки в даному скрипті немає сенсу, аналіз розсіювання і викидів по цих параметрах, можна відстежити на загальних дослдженнях
---