```{r setup, include = FALSE}
library(tidyverse)
library(here)
library(ggh4x)
library(zeallot)

theme_set(
  theme_minimal() +
  theme(
    text = element_text(size = 14),
    plot.title = element_text(margin = margin(0, 0, 30, 0), hjust = 0.5),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 10, 0, 0))
  )
)

dir.create(here("plots", "question6"), recursive = TRUE, showWarnings = FALSE)

splitAt <- function(x, pos) {
  split(x, cumsum(seq_along(x) %in% c(pos))) %>%
  unname()
}
```

Завантажимо датасет:

```{r}
df <- readRDS(here("data", "processed", "air_quality_tidy.rds"))
```

Побудуємо діаграми розсіювання для кожної числової змінної:

```{r} 
df_smooth <- df %>%
  select((where(is.numeric) & !("windspeed" | "winddirec")) | "date") %>%
  group_by(date = as.Date(date)) %>%
  summarise(across(where(is.numeric), ~ median(.x, na.rm = TRUE))) %>%
  pivot_longer(!"date", names_to = "key", values_to = "value") %>%
  group_by(key, ym = date %>% format("%Y-%m")) %>%
  mutate(value_avg = median(value)) %>%
  ungroup()
```

```{r}
plot_line <- function(input_df) {
  input_df %>%
  ggplot() +
  geom_line(aes(x = date, y = value), color = "black") +
  geom_line(
    aes(
      x = ym %>% paste("-01", sep="") %>% as.Date("%Y-%m-%d"), 
      y = value_avg, 
    ),
    color = "#f25309", 
    lwd = 1.5,
    show.legend = TRUE) +
  labs(x = "Date", y = "Value") +
  facet_wrap(~key, scales = "free") +
  facetted_pos_scales(y = c(
    key == "aqi" ~ scale_y_continuous(limits = c(0, 120)),
    key == "so2" ~ scale_y_continuous(limits = c(0, 4))
  )) +
  theme(legend.position = "none")
}

p <- plot_line(df_smooth)

ggsave(
  here("plots", "question6", "line.png"), 
  plot = p, 
  width = 15, height = 15,
  bg = "white",
  dpi = 200)
```

Для презентації:

```{r}
names <- unique(df_smooth$key)
c(names_1, names_2)  %<-% splitAt(names, ceiling(length(names) / 2))

p1 <- plot_line(df_smooth[df_smooth$key %in% names_1, ])
p2 <- plot_line(df_smooth[df_smooth$key %in% names_2, ])

ggsave(
  here("plots", "question6", "line-p1.png"), 
  plot = p1, 
  width = 16, height = 10,
  bg = "white",
  dpi = 200)

ggsave(
  here("plots", "question6", "line-p2.png"), 
  plot = p2, 
  width = 16, height = 10,
  bg = "white",
  dpi = 200)
```