---
Питання №1
Чи впливає швидкість вітру (windspeed) на концентрацію частинок PM2.5 і PM10?
---

```{r setup, include = FALSE}
library(tidyverse)
library(skimr)
library(scales)
library(naniar)
library(corrplot)
library(GGally)
library(patchwork)
library(grid)
library(gridExtra)
library(ggpubr)
library(here)

theme_set(
  theme_minimal() +
  theme(
    text = element_text(size = 20),
    plot.title = element_text(margin = margin(0, 0, 30, 0), hjust = 0.5),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 10, 0, 0))
  )
)

dir.create(here("plots", "question1"), recursive = TRUE, showWarnings = FALSE)
```

# Завантаженя датасету з файлу

```{r}
set.seed(0)
df <- readRDS("data/processed/air_quality_trimmed.rds") %>% slice_sample(n=100000)
```

# Вплив швидкості вітру на концентрацію частинок PM2.5 і PM10

```{r}
windspeed_vs_pm2.5 <- ggplot(df, aes(x = windspeed)) +
  geom_point(aes(y = pm2.5), color = hue_pal()(2)[1], alpha = 0.1, na.rm = TRUE) +
  ylim(0, 400) +
  labs(title = "Вплив вітру на PM2.5", x = "Швидкість вітру (м/с)", y = "Концентрація")

ggsave(
  here("plots", "question1", "wind_speed_vs_pm2_5.png"), 
  windspeed_vs_pm2.5, 
  bg = "white",
  dpi = 200
)
```


```{r}
windspeed_vs_pm10 <- ggplot(df, aes(x = windspeed)) +
  geom_point(aes(y = pm10), color = hue_pal()(2)[2], alpha = 0.1, na.rm = TRUE) +
  ylim(0, 400) +
  labs(title = "Вплив вітру на PM10", x = "Швидкість вітру (м/с)", y = "Концентрація")

ggsave(
  here("plots", "question1", "wind_speed_vs_pm10.png"), 
  windspeed_vs_pm10, 
  bg = "white",
  dpi = 200
)
```

# Розподіли для pm2.5 і pm10 (гістограма)

```{r}
pm2_5_gist <- ggplot(df, aes(x = pm2.5)) +
    geom_histogram(binwidth = 5, fill = "blue", color = "black") +
    labs(title = "Розподіл PM2.5", x = "Концентрація", y = "Частота")

ggsave(here("plots", "question1", "pm2_5_gist.png"), pm2_5_gist, dpi = 200)
```

```{r}
pm10_gist <- ggplot(df, aes(x = pm10)) +
    geom_histogram(binwidth = 5, fill = "blue", color = "black") +
    labs(title = "Розподіл PM10", x = "Концентрація", y = "Частота")

ggsave(here("plots", "question1", "pm10_gist.png"), pm10_gist, dpi = 200)
```

# Кореляційна матриця

```{r}
corr_matrix <- cor(df %>% select(where(is.numeric)), use = "complete.obs", method = "spearman")

png(
  here("plots", "question1", "corr_matrix_plot.png"), 
  width = 720, height = 720)
corrplot(corr_matrix, method = "color", type = "upper", tl.cex = 1, addCoef.col = "black")
dev.off()
```

# Діаграма розсіювання AQI ~ PM2.5

```{r}
aqi_pm2_5_diagram <- ggplot(df, aes(x = pm2.5, y = aqi)) +
    geom_point(alpha = 0.5, color = "blue") +
    geom_smooth(method = "lm", col = "red") +
    labs(title = "Залежність AQI від PM2.5", x = "Концентрація PM2.5", y = "AQI")

ggsave(here("plots", "question1", "aqi_pm2_5_diagram.png"), aqi_pm2_5_diagram, dpi = 200)
```

# Діаграма розсіювання AQI ~ PM10

```{r}
aqi_pm10_diagram <- ggplot(df, aes(x = pm10, y = aqi)) +
    geom_point(alpha = 0.5, color = "blue") +
    geom_smooth(method = "lm", col = "red") +
    labs(title = "Залежність AQI від PM10", x = "Концентрація PM10", y = "AQI")

ggsave(here("plots", "question1", "aqi_pm10_diagram.png"), aqi_pm10_diagram, dpi = 200)
```

# Взаємозв’язок AQI, PM2.5, та інших забруднювачів

```{r}
aqi_pm_polutants <- ggplot(df, aes(x = pm2.5, y = aqi, size = co)) +
    geom_point(alpha = 0.6) +
    labs(title = "Взаємозв’язок AQI, PM2.5, та інших забруднювачів")

ggsave(here("plots", "question1", "aqi_pm_polutants.png"), aqi_pm_polutants, dpi = 200)
```

# QQ-графік для PM2.5

```{r}
qq_pm2_5 <- ggqqplot(df$`pm2.5`, conf.int = TRUE) +
    labs(title = "QQ-графік для PM2.5") +
    theme(
      text = element_text(size = 20)
    )

ggsave(here("plots", "question1", "qq_pm2_5.png"), qq_pm2_5, dpi = 200)
```

# QQ-графік для PM10

```{r}
qq_pm10 <- ggqqplot(df$`pm10`, conf.int = TRUE) +
    labs(title = "QQ-графік для PM10") +
    theme(
      text = element_text(size = 20)
    )

ggsave(here("plots", "question1", "qq_pm10.png"), qq_pm10, dpi = 200)
```

# Scatter plot (вплив швидкості і напрямку вітру на PM2.5 і PM10 по регіонах)

```{r}
scatter_pm2_5_region <- ggplot(df, aes(x = windspeed, y = pm2.5, color = winddirec)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~county) +
  labs(title = "Вплив швидкості вітру на PM2.5 у різних регіонах",
       x = "Швидкість вітру (windspeed)",
       y = "PM2.5",
       color = "Напрямок вітру") +
  theme(strip.text.x = element_text(size = 7.5, hjust = 0.5))

ggsave(
  here("plots", "question1", "scatter_pm2_5_region.png"),
  scatter_pm2_5_region,
  dpi = 200,
  width = 16,
  height = 10,
  bg = "white"
)
```

```{r}
scatter_pm10_region <- ggplot(df, aes(x = windspeed, y = pm10, color = winddirec)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~county) +
  labs(title = "Вплив швидкості вітру на PM10 у різних регіонах",
       x = "Швидкість вітру (windspeed)",
       y = "PM10",
       color = "Напрямок вітру") +
  theme(strip.text.x = element_text(size = 7.5, hjust = 0.5))

ggsave(
  here("plots", "question1", "scatter_pm10_region.png"),
  scatter_pm10_region,
  width = 16,
  height = 10,
  dpi = 200,
  bg = "white"
)
```
