```{r}
library(np)           # Непараметрична регресія
library(KernSmooth)   # Ядрова регресія
library(mgcv)         # GAM моделі
library(ggplot2)      # Графіки
library(dplyr)        # Обробка даних
library(gridExtra)    # Компонування графіків
library(reshape2)     # Перетворення даних
library(corrplot)     # Кореляційні графіки
library(here)         # Для шляхів до файлів

theme_set(
  theme_minimal() +
  theme(
    text = element_text(size = 20),
    plot.title = element_text(margin = margin(0, 0, 30, 0), hjust = 0.5),
    axis.title.x = element_text(margin = margin(20, 0, 0, 0)),
    axis.title.y = element_text(margin = margin(0, 10, 0, 0)),
    panel.spacing = unit(2, "lines"),
  )
)

# Створення папки для збереження результатів
output_path <- here("data", "models")
if (!dir.exists(output_path)) {
  dir.create(output_path, recursive = TRUE)
}
```

## Підготовка даних
```{r}
# Завантаження даних
df <- readRDS(here("data", "processed", "model_df.rds"))

# Фільтрування даних за NA
df <- df %>% drop_na()

# Вибір топ-8 counties за середнім AQI
counties <- df %>%
  group_by(county) %>%
  summarize(aqi = mean(aqi, na.rm = TRUE)) %>%
  ungroup() %>%
  arrange(desc(aqi)) %>%
  head(n = 8)

counties <- counties$county

# Фільтрування даних за обраними counties
df <- df %>% subset(county %in% counties)

# Додавання колонки windspeed^2
df$windspeed2 <- df$windspeed^2

cat("Загальна кількість спостережень:", nrow(df), "\n")
cat("Кількість унікальних counties:", length(unique(df$county)), "\n")
cat("Кількість унікальних sitename:", length(unique(df$sitename)), "\n")
cat("Топ-8 counties за AQI:\n")
print(counties)
```

## Розділення на навчальну і тестову вибірки
```{r}
# Встановлення seed для відтворюваності
set.seed(123)

# Обираємо частину рядків у випадковому порядку
df_smol <- sample_n(df, 10000)
# df_smol <- sample_n(df, nrow(df))

# Ділимо на навчальну і тестову частини
bound <- floor(nrow(df_smol) * 0.7)
df_train <- df_smol[1:bound, ]
df_test <- df_smol[(bound+1):nrow(df_smol), ]
```

## Оцінка моделі
```{r}
# Частково лінійна модель:
#   Параметрично: reform_days, windspeed, windspeed^2
#   Непараметрично: jul_days

bw <- npplregbw(
  aqi ~ reform_days + windspeed + windspeed2 | jul_days,
  data = df_train, regtype = "ll")

model_nppl <- npplreg(bw)

summary(model_nppl)

save(model_nppl, file = here("data", "models", "model_nppl.rda"))
```

## Побудова графіків
```{r}
# Функція для створення графіка непараметричної залежності
create_nonparam_plot <- function(data_train, data_test, x_name, y_name, model_nppl) {
  
  # Фіксуємо інші змінні на медіанних значеннях
  data_test_fixed <- data_test %>% arrange(!!sym(x_name))
  for (col in names(data_test)) {
    if (col == x_name || col == y_name) next
    if (is.numeric(data_test[[col]])) {
      data_test_fixed[[col]] <- median(data_test[[col]], na.rm = TRUE)
    } else if (is.factor(data_test[[col]])) {
      data_test_fixed[[col]] <- names(sort(table(data_test[[col]]), decreasing = TRUE))[1]
    }
  }
  
  # Перетворимо Y = Z*b + m(X) на Y - Z*b = m(X), тобто врахуємо параметричну частину моделі в її лівій частині.
  data_train_sub <- data_train
  for (col in names(data_test)) {
    if (col == x_name || col == y_name) next
    if (!(col %in% names(model_nppl$xcoef))) next
    data_train_sub[[y_name]] = data_train_sub[[y_name]] - model_nppl$xcoef[col] * data_train_sub[[col]]
  }

  # Здійснимо непараметричну частину регресії
  formula <- as.formula(paste(y_name, "~", x_name))
  bw <- npregbw(formula, data = data_train_sub, regtype = "ll")
  model_np <- npreg(bw)
  pred <- predict(model_np, newdata = data_test_fixed, se.fit = TRUE)
  
  # Створення DataFrame для графіка
  plot_data <- data.frame(
    x = data_test_fixed[[x_name]],
    y_real = data_test_fixed[[y_name]],
    y_fit = pred$fit,
    ci_l = pred$fit - qnorm(0.975) * pred$se.fit,
    ci_u = pred$fit + qnorm(0.975) * pred$se.fit
  )

  # Створення графіка
  ggplot(plot_data, aes(x = x, y = y_real)) +
    geom_point(alpha=0.1, size=2) +
    geom_line(aes(x = x, y = y_fit), color = "blue", size = 1) +
    geom_ribbon(aes(ymin = ci_l, ymax = ci_u), fill = "blue", alpha = 0.3) +
    labs(title = "Частково лінійна модель", x = x_name, y = "AQI")
}
```

```{r}
load(here("data", "models", "model_nppl.rda"))
p <- create_nonparam_plot(df_train, df_test, "jul_days", "aqi", model_nppl)

ggsave(
    here("plots","lab4", "nppl.png"),
    p,
    width = 15,
    height = 10,
    bg = "white")
```

## Таблиці
```{r}
nppl_to_modelsummary_compatible <- function(model_nppl) {
  model_nppl_ti <- tibble(term = names(model_nppl$xcoef),
                          estimate = model_nppl$xcoef,
                          std.error = model_nppl$xcoeferr,
                          p.value = 2*pnorm(-abs(estimate/std.error)))
  model_nppl_gl <- data.frame(Num.Obs. = model_nppl$nobs)
  mod_nppl <- list(tidy = model_nppl_ti, glance = model_nppl_gl)
  class(mod_nppl) <- "modelsummary_list"
  return(mod_nppl)
}
```

```{r}
load(here("data", "models", "model_nppl.rda"))
modelsummary(
  list("1" = nppl_to_modelsummary_compatible(model_nppl)),
  stars = TRUE,
  output = 'latex',
  gof_omit = "^(?!Num\\.Obs\\.)",
  fmt = 6
)
```
